---
# Maybe later we will put the upload in other part
# - name: compress the upload directory
#   command: 7z a /tmp/wp-upload-backup.7z /srv/www
#   become: yes

# # TODO use rsync 
# - name: fetch the backup
#   fetch:
#     src: /tmp/wp-upload-backup.7z
#     dest: .backup/wp-upload-backup.7z
#     flat: yes

# - name: clean the 7z backup
#   file: path=/tmp/wp-upload-backup.7z state=absent
#   become: yes
