---
- name: install wordpress
  apt: pkg=wordpress state=latest
- name: install mysql db tools
  apt: pkg=python-mysqldb
- name: create wordpress database (u/p)
  mysql_db: name={{ wordpress_db_name }} login_user={{ user }} login_password={{ password }} login_host={{ host }}
- name: create wordpress db account (u/p)
  mysql_user: name={{ wordpress_user }} password={{ wordpress_password }} host=% priv={{ wordpress_db_name }}.*:ALL login_user={{ user }} login_password={{ password }} login_host={{ host }}
- name: create wordpress symlink
  file: state=link path=/var/www/wordpress src=/usr/share/wordpress
- name: set permissions on wordpress folder
  file: owner=www-data recurse=yes path=/usr/share/wordpress state=directory